// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: control.proto

package controlpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Login struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Credentials   []byte                 `protobuf:"bytes,1,opt,name=credentials,proto3" json:"credentials,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Login) Reset() {
	*x = Login{}
	mi := &file_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Login) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Login) ProtoMessage() {}

func (x *Login) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Login.ProtoReflect.Descriptor instead.
func (*Login) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{0}
}

func (x *Login) GetCredentials() []byte {
	if x != nil {
		return x.Credentials
	}
	return nil
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	PlayerId      uint32                 `protobuf:"varint,3,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	SessionToken  string                 `protobuf:"bytes,4,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`
	UdpEndpoint   string                 `protobuf:"bytes,5,opt,name=udp_endpoint,json=udpEndpoint,proto3" json:"udp_endpoint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{1}
}

func (x *LoginResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *LoginResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *LoginResponse) GetPlayerId() uint32 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *LoginResponse) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

func (x *LoginResponse) GetUdpEndpoint() string {
	if x != nil {
		return x.UdpEndpoint
	}
	return ""
}

type UdpHandshake struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      uint32                 `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	SessionToken  string                 `protobuf:"bytes,2,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UdpHandshake) Reset() {
	*x = UdpHandshake{}
	mi := &file_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UdpHandshake) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UdpHandshake) ProtoMessage() {}

func (x *UdpHandshake) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UdpHandshake.ProtoReflect.Descriptor instead.
func (*UdpHandshake) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{2}
}

func (x *UdpHandshake) GetPlayerId() uint32 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *UdpHandshake) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

type UdpHandshakeAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	PlayerId      uint32                 `protobuf:"varint,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UdpHandshakeAck) Reset() {
	*x = UdpHandshakeAck{}
	mi := &file_control_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UdpHandshakeAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UdpHandshakeAck) ProtoMessage() {}

func (x *UdpHandshakeAck) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UdpHandshakeAck.ProtoReflect.Descriptor instead.
func (*UdpHandshakeAck) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{3}
}

func (x *UdpHandshakeAck) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *UdpHandshakeAck) GetPlayerId() uint32 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

type Ping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nonce         uint64                 `protobuf:"varint,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ping) Reset() {
	*x = Ping{}
	mi := &file_control_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{4}
}

func (x *Ping) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

type Pong struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nonce         uint64                 `protobuf:"varint,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pong) Reset() {
	*x = Pong{}
	mi := &file_control_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pong) ProtoMessage() {}

func (x *Pong) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pong.ProtoReflect.Descriptor instead.
func (*Pong) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{5}
}

func (x *Pong) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

// ClientFrame is the wire-level wrapper for every message sent from
// client to server, over both TCP and UDP. The Godot client constructs
// this and the library unmarshals it on receive.
type ClientFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Body:
	//
	//	*ClientFrame_Login
	//	*ClientFrame_UdpHandshake
	//	*ClientFrame_Pong
	//	*ClientFrame_GamePayload
	Body          isClientFrame_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientFrame) Reset() {
	*x = ClientFrame{}
	mi := &file_control_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientFrame) ProtoMessage() {}

func (x *ClientFrame) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientFrame.ProtoReflect.Descriptor instead.
func (*ClientFrame) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{6}
}

func (x *ClientFrame) GetBody() isClientFrame_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *ClientFrame) GetLogin() *Login {
	if x != nil {
		if x, ok := x.Body.(*ClientFrame_Login); ok {
			return x.Login
		}
	}
	return nil
}

func (x *ClientFrame) GetUdpHandshake() *UdpHandshake {
	if x != nil {
		if x, ok := x.Body.(*ClientFrame_UdpHandshake); ok {
			return x.UdpHandshake
		}
	}
	return nil
}

func (x *ClientFrame) GetPong() *Pong {
	if x != nil {
		if x, ok := x.Body.(*ClientFrame_Pong); ok {
			return x.Pong
		}
	}
	return nil
}

func (x *ClientFrame) GetGamePayload() []byte {
	if x != nil {
		if x, ok := x.Body.(*ClientFrame_GamePayload); ok {
			return x.GamePayload
		}
	}
	return nil
}

type isClientFrame_Body interface {
	isClientFrame_Body()
}

type ClientFrame_Login struct {
	Login *Login `protobuf:"bytes,1,opt,name=login,proto3,oneof"`
}

type ClientFrame_UdpHandshake struct {
	UdpHandshake *UdpHandshake `protobuf:"bytes,2,opt,name=udp_handshake,json=udpHandshake,proto3,oneof"`
}

type ClientFrame_Pong struct {
	Pong *Pong `protobuf:"bytes,3,opt,name=pong,proto3,oneof"`
}

type ClientFrame_GamePayload struct {
	// game_payload is the marshaled user-defined top-level
	// ClientMessage. The library does not parse it itself; it is
	// unmarshaled into Config.ClientMessagePrototype and dispatched.
	GamePayload []byte `protobuf:"bytes,16,opt,name=game_payload,json=gamePayload,proto3,oneof"`
}

func (*ClientFrame_Login) isClientFrame_Body() {}

func (*ClientFrame_UdpHandshake) isClientFrame_Body() {}

func (*ClientFrame_Pong) isClientFrame_Body() {}

func (*ClientFrame_GamePayload) isClientFrame_Body() {}

// ServerFrame is the wire-level wrapper for every message sent from
// server to client.
type ServerFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Body:
	//
	//	*ServerFrame_LoginResponse
	//	*ServerFrame_UdpHandshakeAck
	//	*ServerFrame_Ping
	//	*ServerFrame_GamePayload
	Body          isServerFrame_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerFrame) Reset() {
	*x = ServerFrame{}
	mi := &file_control_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerFrame) ProtoMessage() {}

func (x *ServerFrame) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerFrame.ProtoReflect.Descriptor instead.
func (*ServerFrame) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{7}
}

func (x *ServerFrame) GetBody() isServerFrame_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *ServerFrame) GetLoginResponse() *LoginResponse {
	if x != nil {
		if x, ok := x.Body.(*ServerFrame_LoginResponse); ok {
			return x.LoginResponse
		}
	}
	return nil
}

func (x *ServerFrame) GetUdpHandshakeAck() *UdpHandshakeAck {
	if x != nil {
		if x, ok := x.Body.(*ServerFrame_UdpHandshakeAck); ok {
			return x.UdpHandshakeAck
		}
	}
	return nil
}

func (x *ServerFrame) GetPing() *Ping {
	if x != nil {
		if x, ok := x.Body.(*ServerFrame_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

func (x *ServerFrame) GetGamePayload() []byte {
	if x != nil {
		if x, ok := x.Body.(*ServerFrame_GamePayload); ok {
			return x.GamePayload
		}
	}
	return nil
}

type isServerFrame_Body interface {
	isServerFrame_Body()
}

type ServerFrame_LoginResponse struct {
	LoginResponse *LoginResponse `protobuf:"bytes,1,opt,name=login_response,json=loginResponse,proto3,oneof"`
}

type ServerFrame_UdpHandshakeAck struct {
	UdpHandshakeAck *UdpHandshakeAck `protobuf:"bytes,2,opt,name=udp_handshake_ack,json=udpHandshakeAck,proto3,oneof"`
}

type ServerFrame_Ping struct {
	Ping *Ping `protobuf:"bytes,3,opt,name=ping,proto3,oneof"`
}

type ServerFrame_GamePayload struct {
	GamePayload []byte `protobuf:"bytes,16,opt,name=game_payload,json=gamePayload,proto3,oneof"`
}

func (*ServerFrame_LoginResponse) isServerFrame_Body() {}

func (*ServerFrame_UdpHandshakeAck) isServerFrame_Body() {}

func (*ServerFrame_Ping) isServerFrame_Body() {}

func (*ServerFrame_GamePayload) isServerFrame_Body() {}

var File_control_proto protoreflect.FileDescriptor

const file_control_proto_rawDesc = "" +
	"\n" +
	"\rcontrol.proto\x12\x10godotnet.control\")\n" +
	"\x05Login\x12 \n" +
	"\vcredentials\x18\x01 \x01(\fR\vcredentials\"\xa9\x01\n" +
	"\rLoginResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12\x1b\n" +
	"\tplayer_id\x18\x03 \x01(\rR\bplayerId\x12#\n" +
	"\rsession_token\x18\x04 \x01(\tR\fsessionToken\x12!\n" +
	"\fudp_endpoint\x18\x05 \x01(\tR\vudpEndpoint\"P\n" +
	"\fUdpHandshake\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\rR\bplayerId\x12#\n" +
	"\rsession_token\x18\x02 \x01(\tR\fsessionToken\">\n" +
	"\x0fUdpHandshakeAck\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x1b\n" +
	"\tplayer_id\x18\x02 \x01(\rR\bplayerId\"\x1c\n" +
	"\x04Ping\x12\x14\n" +
	"\x05nonce\x18\x01 \x01(\x04R\x05nonce\"\x1c\n" +
	"\x04Pong\x12\x14\n" +
	"\x05nonce\x18\x01 \x01(\x04R\x05nonce\"\xe0\x01\n" +
	"\vClientFrame\x12/\n" +
	"\x05login\x18\x01 \x01(\v2\x17.godotnet.control.LoginH\x00R\x05login\x12E\n" +
	"\rudp_handshake\x18\x02 \x01(\v2\x1e.godotnet.control.UdpHandshakeH\x00R\fudpHandshake\x12,\n" +
	"\x04pong\x18\x03 \x01(\v2\x16.godotnet.control.PongH\x00R\x04pong\x12#\n" +
	"\fgame_payload\x18\x10 \x01(\fH\x00R\vgamePayloadB\x06\n" +
	"\x04body\"\x83\x02\n" +
	"\vServerFrame\x12H\n" +
	"\x0elogin_response\x18\x01 \x01(\v2\x1f.godotnet.control.LoginResponseH\x00R\rloginResponse\x12O\n" +
	"\x11udp_handshake_ack\x18\x02 \x01(\v2!.godotnet.control.UdpHandshakeAckH\x00R\x0fudpHandshakeAck\x12,\n" +
	"\x04ping\x18\x03 \x01(\v2\x16.godotnet.control.PingH\x00R\x04ping\x12#\n" +
	"\fgame_payload\x18\x10 \x01(\fH\x00R\vgamePayloadB\x06\n" +
	"\x04bodyB;Z9github.com/jordanstites/godotnet/internal/proto;controlpbb\x06proto3"

var (
	file_control_proto_rawDescOnce sync.Once
	file_control_proto_rawDescData []byte
)

func file_control_proto_rawDescGZIP() []byte {
	file_control_proto_rawDescOnce.Do(func() {
		file_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_control_proto_rawDesc), len(file_control_proto_rawDesc)))
	})
	return file_control_proto_rawDescData
}

var file_control_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_control_proto_goTypes = []any{
	(*Login)(nil),           // 0: godotnet.control.Login
	(*LoginResponse)(nil),   // 1: godotnet.control.LoginResponse
	(*UdpHandshake)(nil),    // 2: godotnet.control.UdpHandshake
	(*UdpHandshakeAck)(nil), // 3: godotnet.control.UdpHandshakeAck
	(*Ping)(nil),            // 4: godotnet.control.Ping
	(*Pong)(nil),            // 5: godotnet.control.Pong
	(*ClientFrame)(nil),     // 6: godotnet.control.ClientFrame
	(*ServerFrame)(nil),     // 7: godotnet.control.ServerFrame
}
var file_control_proto_depIdxs = []int32{
	0, // 0: godotnet.control.ClientFrame.login:type_name -> godotnet.control.Login
	2, // 1: godotnet.control.ClientFrame.udp_handshake:type_name -> godotnet.control.UdpHandshake
	5, // 2: godotnet.control.ClientFrame.pong:type_name -> godotnet.control.Pong
	1, // 3: godotnet.control.ServerFrame.login_response:type_name -> godotnet.control.LoginResponse
	3, // 4: godotnet.control.ServerFrame.udp_handshake_ack:type_name -> godotnet.control.UdpHandshakeAck
	4, // 5: godotnet.control.ServerFrame.ping:type_name -> godotnet.control.Ping
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_control_proto_init() }
func file_control_proto_init() {
	if File_control_proto != nil {
		return
	}
	file_control_proto_msgTypes[6].OneofWrappers = []any{
		(*ClientFrame_Login)(nil),
		(*ClientFrame_UdpHandshake)(nil),
		(*ClientFrame_Pong)(nil),
		(*ClientFrame_GamePayload)(nil),
	}
	file_control_proto_msgTypes[7].OneofWrappers = []any{
		(*ServerFrame_LoginResponse)(nil),
		(*ServerFrame_UdpHandshakeAck)(nil),
		(*ServerFrame_Ping)(nil),
		(*ServerFrame_GamePayload)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_control_proto_rawDesc), len(file_control_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_control_proto_goTypes,
		DependencyIndexes: file_control_proto_depIdxs,
		MessageInfos:      file_control_proto_msgTypes,
	}.Build()
	File_control_proto = out.File
	file_control_proto_goTypes = nil
	file_control_proto_depIdxs = nil
}
